version: "3"

services:
  rabbit:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - app-network

  microservice-compra:
    image: thiagorabelojf/avancadev-mircoservice-1
    ports:
      - 9090:9090
    restart: on-failure
    networks:
      - app-network
    depends_on:
      - rabbit
    links: ["rabbit"]

  microservice-pagamento:
    image: thiagorabelojf/avancadev-mircoservice-2
    restart: on-failure
    networks:
      - app-network
    depends_on:
      - rabbit
    links: ["rabbit"]

  microservice-coupon:
    image: thiagorabelojf/avancadev-mircoservice-3
    networks:
      - app-network
    ports:
      - 9092:9092

networks:
  app-network:
    driver: bridge
