apiVersion: v1
kind: ConfigMap
metadata:
  name: microservico-conf
  labels:
    name: microservico-conf
data:
  env: |
    RABBITMQ_DEFAULT_HOST=rabbitmq-service
    RABBITMQ_DEFAULT_PORT=5672
    RABBITMQ_DEFAULT_VHOST=/
    RABBITMQ_CONSUMER_NAME=compra-microservice
    RABBITMQ_CONSUMER_QUEUE_NAME=orders
    RABBITMQ_NOTIFICATION_EX=amq.direct
    RABBITMQ_NOTIFICATION_ROUTING_KEY=jobs
    RABBITMQ_DLX=dlx
