apiVersion: v1
kind: Service
metadata:
  name: microservico-compra-service
spec:
  type: LoadBalancer
  selector:
    app: microservico-compra
  ports:
    - port: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: micro-servico-coupon
spec:
  selector:
    app: micro-servico-coupon
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    app: rabbitmq-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 15672
      nodePort: 30081
    - name: amqp
      protocol: TCP
      port: 5672
      nodePort: 30082
  selector:
    app: rabbitmq
